# Theme Settings
remote_theme: lewismiddleton/cayman-dark
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Site info
title: "Mars-Lab"
description: "RFIC • RFID • Microelectronics • Phased Arrays • Wireless Systems"
url: "https://marslabbgu.github.io"

# Appearance
show_downloads: false
google_analytics: 

# Fix for the </p> issue: 
# We'll set kramdown to be less aggressive with HTML blocks
kramdown:
  input: GFM
  syntax_highlighter: rouge
  # Removing parse_block_html: true often fixes the stray </p> 
  # Use markdown="1" in your HTML tags instead if you need it.

# Collections
collections:
  projects:
    output: true
  publications:
    output: true
