# Theme
remote_theme: pages-themes/cayman@v0.2.0
# Plugins
plugins:
  - jekyll-remote-theme
# Site info
title: "Mars-Lab"
description: "RFIC • RFID • Microelectronics • Phased Arrays • Wireless Systems"
# Appearance
show_downloads: false

# Custom styling (important)
google_analytics: 
# Navigation 
header_pages:
  - index.md
  - projects.md
  - publications.md

# Markdown rendering
markdown: kramdown
highlighter: rouge

# Enable HTML inside markdown 
kramdown:
  input: GFM
  parse_block_html: true

# Collections 
collections:
  projects:
    output: true
  publications:
    output: true
